import { dayOneSlides, type CampSlide } from "./dayOne";

export interface CampDay {
  number: number;
  title: string;
  subtitle: string;
  slides: CampSlide[];
}

const dayTwoSlides: CampSlide[] = [
  { id: "component-quick-fire", title: "Go over: component quick fire", heading: "Name that component", kicker: "TEAM CHALLENGE", body: "Your instructor shows five parts. Teams get 30 seconds to name each part and explain one job it performs.", icon: "?", tone: "green" },
  { id: "day-one-connection", title: "Go over: connect yesterday", heading: "Hardware makes AI real", tone: "light", bullets: ["Yesterday: AI uses patterns to make predictions.", "Today: we ask what kind of hardware does the work.", "Key question: why do some chips run AI better than others?", "Watch for the idea of parallel work." ] },
  { id: "brains-prediction", title: "Go over: prediction poll", heading: "Which part matters most for AI?", kicker: "VOTE FIRST", body: "Vote CPU, GPU, RAM, storage, or all of them. Keep your answer visible. You may change your mind by the end of the lesson, but you must explain why.", icon: "POLL", tone: "purple" },
  { id: "ai-history-winter", title: "History of AI: high hopes and slowdowns", heading: "AI has had boom and winter cycles", tone: "pink", bullets: ["Early AI systems solved narrow problems but struggled outside their rules.", "Funding and excitement dropped during AI winters.", "The pattern repeated: big promises, hard reality, better tools later.", "This teaches us to be excited and skeptical at the same time." ] },
  { id: "ai-history-deep-blue", title: "History of AI: game milestones", heading: "Games became test labs", tone: "green", bullets: ["1997 — Deep Blue beat Garry Kasparov at chess.", "Game AI showed that search, rules, and compute could beat experts in narrow tasks.", "Winning a game did not mean the system understood the world.", "Narrow success is powerful, but it is not general intelligence." ] },
  { id: "ai-history-gpu-deep-learning", title: "History of AI: GPUs change the pace", heading: "Parallel math unlocks deep learning", tone: "purple", bullets: ["Neural networks need huge numbers of similar math operations.", "GPUs were built to do many similar operations at once.", "As data grew and GPUs improved, deep learning systems improved quickly.", "The hardware story and the AI story are connected." ] },
  { id: "what-neural-network", title: "What is a neural network?", heading: "A stack of adjustable pattern filters", tone: "light", body: "A neural network transforms numbers through layers. During training, the numbers are adjusted so outputs become more useful for examples like images, words, or sounds.", icon: "NET" },
  { id: "where-ai-runs", title: "Where does AI run?", heading: "Device, classroom computer, or cloud data center", tone: "green", cards: [ { icon: "📱", title: "On-device", text: "Fast and private, but limited by battery and memory." }, { icon: "PC", title: "Local computer", text: "Great for camp learning and offline experiments." }, { icon: "☁️", title: "Cloud", text: "Powerful, but depends on networks, cost, and data rules." } ] },
  { id: "why-cpu-gpu", title: "Why do GPUs help AI?", heading: "AI repeats lots of math at the same time", tone: "pink", bullets: ["Text, image, and sound models use vectors and matrices.", "A CPU is flexible and strong for varied instructions.", "A GPU is strong when thousands of similar calculations can run together.", "The best system uses the right part for the right job." ] },
  { id: "cpu", title: "CPU: the generalist", heading: "A few powerful workers", tone: "light", bullets: ["CPU means Central Processing Unit.", "Modern CPUs contain several powerful cores that handle complex instructions.", "They are excellent at decisions, branching logic, and running programs.", "Think of a CPU as a small team of experts who can solve many different problems." ] },
  { id: "gpu", title: "GPU: parallel muscle", heading: "Thousands of smaller workers", tone: "purple", bullets: ["GPU means Graphics Processing Unit.", "A GPU performs many similar calculations at the same time.", "Rendering pixels and running neural networks both rely heavily on matrix math.", "Think of a GPU as thousands of specialists working in parallel." ] },
  { id: "cpu-vs-gpu", title: "CPU versus GPU", heading: "Choose the right kind of worker", tone: "pink", cards: [ { icon: "CPU", title: "Flexible", text: "Handles complex, changing instructions and operating-system work." }, { icon: "GPU", title: "Parallel", text: "Repeats lots of similar math operations simultaneously." }, { icon: "AI", title: "Together", text: "The CPU runs the app while the GPU can accelerate model calculations." } ] },
  { id: "training-inference", title: "Training and inference", heading: "Learning first, answering later", tone: "green", bullets: ["Training shows a model many examples and adjusts numerical weights when predictions are wrong.", "Training large models can require many GPUs, lots of energy, and weeks of work.", "Inference uses the finished model to answer a new request.", "REACT Camp uses inference: the model was trained elsewhere and runs locally through Ollama." ] },
  { id: "parameters", title: "What is in a model file?", heading: "Billions of learned numbers", tone: "light", body: "A parameter is a learned numerical value. A 3B model has roughly three billion parameters. Quantization stores those values more compactly so useful models can run on ordinary computers.", icon: "3B" },
  { id: "model-fit", title: "Will the model fit?", heading: "Memory sets the practical limit", tone: "purple", bullets: ["The model and its working context must fit in available RAM or VRAM.", "Smaller models start faster and are safer on donated or older laptops.", "Larger context windows consume more memory even when the model file is unchanged.", "The best camp model is the one that responds reliably on the actual hardware." ] },
  { id: "ethics-energy", title: "Ethics question 1", heading: "How much energy should AI use?", tone: "pink", bullets: ["Training and running models use electricity and hardware resources.", "Some uses are valuable enough to justify the cost; some are wasteful.", "Who should decide when an AI system is worth the energy?", "How could local, smaller models reduce the footprint for some tasks?" ] },
  { id: "ethics-access", title: "Ethics question 2", heading: "Who gets access to powerful AI?", tone: "light", body: "If only wealthy schools or companies can use the strongest models, who falls behind? List one way open-source tools, local models, or public education could make access more fair.", icon: "FAIR" },
  { id: "teach-back-two", title: "Ethics question 3 + teach back", heading: "Why can a GPU help run AI?", kicker: "EXIT TICKET", body: "Explain the answer to a partner without using the word faster. Include parallel work, one limitation of local hardware, and one responsibility that comes with powerful compute.", tone: "green" },
];

const dayThreeSlides: CampSlide[] = [
  { id: "ram-storage-vote", title: "Go over: RAM or storage?", heading: "Same thing or totally different?", kicker: "VOTE, THEN DEFEND IT", body: "RAM and storage both hold data, but they solve different problems. Write one prediction before revealing the answer.", icon: "RAM", tone: "green" },
  { id: "day-two-connection", title: "Go over: from brains to workspace", heading: "The chip cannot work without room", tone: "light", bullets: ["Yesterday: CPUs and GPUs do different kinds of work.", "Today: memory and storage decide what can load, run, and be saved.", "AI adds a new pressure: model files and context need space.", "Prompt quality also changes what the model can do." ] },
  { id: "prompt-before-after", title: "Go over: prompt before/after", heading: "Small wording changes can change the result", tone: "purple", body: "Ask the same AI two versions: 'Explain RAM' and 'Explain RAM to a beginner using a desk analogy and one warning about upgrades.' Compare accuracy, usefulness, and length.", icon: "A/B" },
  { id: "ai-history-imagenet", title: "History of AI: data gets big", heading: "Large labeled datasets changed vision AI", tone: "pink", bullets: ["Image recognition improved when models could train on many labeled examples.", "Competitions helped researchers compare systems fairly.", "Better data plus better GPUs made deep learning practical.", "The lesson: AI progress often needs data, compute, and evaluation together." ] },
  { id: "ai-history-transformer", title: "History of AI: attention", heading: "Transformers changed language AI", tone: "green", bullets: ["Transformer models use attention to connect words across a context.", "They can learn patterns in language, code, and other sequences.", "Modern chatbots are built from this family of models.", "The context you provide becomes part of what the model can use." ] },
  { id: "ai-history-chatbots", title: "History of AI: chat becomes common", heading: "Useful interfaces made AI feel real", tone: "purple", bullets: ["People did not need to write code to try language models.", "Chat interfaces made prompting a new everyday skill.", "The same ease of use also made misinformation and overtrust easier.", "That is why prompt skill and verification matter." ] },
  { id: "what-token-context", title: "What are tokens and context?", heading: "The model reads chunks, not whole understanding", tone: "light", bullets: ["A token is a piece of text such as a word, part of a word, or punctuation.", "The context window is how much text the model can consider at once.", "Longer context uses more memory and can still miss details.", "Good prompts put the most important information clearly in the context." ] },
  { id: "where-memory-lives", title: "Where does AI memory live?", heading: "Model memory is not the same as human memory", tone: "green", cards: [ { icon: "RAM", title: "Runtime", text: "The active model and current conversation use memory." }, { icon: "SSD", title: "Storage", text: "Model files and saved projects stay after shutdown." }, { icon: "CTX", title: "Context", text: "The prompt gives temporary information for this answer." } ] },
  { id: "why-prompting", title: "Why prompts matter", heading: "The model fills gaps with assumptions", tone: "pink", bullets: ["A vague prompt leaves the AI guessing your goal, level, and format.", "A strong prompt includes role, context, task, format, and limits.", "Better prompts reduce confusion but do not guarantee truth.", "Prompting is a thinking skill, not a magic spell." ] },
  { id: "ram-workspace", title: "RAM: the workspace", heading: "The desk you are using right now", tone: "purple", bullets: ["Open programs and active data live in RAM.", "RAM is volatile: its contents disappear when power is removed.", "More RAM lets the computer keep more active work available.", "A local AI model must fit in memory while it is running." ] },
  { id: "ram-compatibility", title: "Compatibility matters", heading: "Never force a memory module", tone: "pink", bullets: ["DDR generations have different electrical designs and notch positions.", "Check the motherboard manual before selecting an upgrade.", "Use matching modules in the recommended slots for dual-channel operation.", "Press evenly until the retaining clips lock; stop if alignment is wrong." ] },
  { id: "storage-types", title: "Storage: keep it after shutdown", heading: "HDD, SATA SSD, and NVMe", tone: "light", cards: [ { icon: "HDD", title: "Hard drive", text: "Mechanical, inexpensive capacity, and the slowest option." }, { icon: "SSD", title: "SATA SSD", text: "Flash storage with a large speed improvement over an HDD." }, { icon: "M.2", title: "NVMe SSD", text: "Compact storage connected through fast PCIe lanes." } ] },
  { id: "upgrade-plan", title: "Plan an upgrade", heading: "Evidence before parts", tone: "green", bullets: ["Identify the motherboard and computer model.", "Record the current RAM type, capacity, and occupied slots.", "Check storage connectors, physical clearance, and power needs.", "Compare the upgrade cost with the performance problem it should solve.", "Ask an instructor to confirm compatibility before installation." ] },
  { id: "prompt-anatomy", title: "Prompt engineering", heading: "Role + context + task + format + constraints", tone: "purple", cards: [ { icon: "1", title: "Role", text: "Who should the AI act like?" }, { icon: "2", title: "Context", text: "What does it need to know?" }, { icon: "3", title: "Task", text: "What should it accomplish?" }, { icon: "4", title: "Format", text: "How should the answer be organized?" }, { icon: "5", title: "Limits", text: "What level, length, or rules matter?" } ] },
  { id: "prompt-comparison", title: "Run the comparison", heading: "Specific context changes the answer", tone: "pink", bullets: ["Basic: How do I make a quiz game?", "Better: Help me make a five-question HTML and JavaScript quiz. I am a beginner.", "Best: I already have a questions array. Write only the function that displays one question, records an answer, and explains each line with a comment.", "Send all three in AI Lab and compare usefulness, assumptions, and length." ] },
  { id: "ethics-hallucination", title: "Ethics question 1", heading: "What if AI sounds right but is wrong?", tone: "light", bullets: ["A hallucination is an answer that appears confident but is false or unsupported.", "Who is responsible for checking before sharing?", "What topics require extra care: health, law, safety, grades, money, identity?", "Create a two-step fact-check rule for your team." ] },
  { id: "ethics-data-leftovers", title: "Ethics question 2", heading: "What traces do prompts leave?", tone: "purple", body: "Even when a tool feels private, prompts can reveal names, habits, schoolwork, or personal situations. Rewrite a risky prompt into a safe practice prompt using fake data.", icon: "SAFE" },
  { id: "upgrade-teach-back", title: "Ethics question 3 + teach back", heading: "Recommend one upgrade", kicker: "EXIT TICKET", body: "Choose a slow computer scenario. Recommend RAM, storage, or neither. Support it with two pieces of evidence and one privacy or accuracy rule for using AI to research the part.", tone: "green" },
];

const dayFourSlides: CampSlide[] = [
  { id: "reassembly-memory", title: "Go over: reassembly challenge", heading: "List the safe order from memory", kicker: "60 SECONDS", body: "Work as a group. Include the CPU cooler, RAM, storage, GPU, front-panel connectors, power cables, fans, and a final inspection.", icon: "10", tone: "green" },
  { id: "day-three-connection", title: "Go over: upgrade logic", heading: "Every build is a chain of decisions", tone: "light", bullets: ["Yesterday you matched symptoms to RAM, storage, or prompting.", "Today you reassemble, power on, and troubleshoot safely.", "AI can coach, but it cannot see every connector unless you describe it clearly.", "Evidence beats guessing." ] },
  { id: "troubleshoot-mindset", title: "Go over: troubleshooting mindset", heading: "Change one variable at a time", tone: "purple", body: "When something fails, do not randomly change ten things. Observe, form one hypothesis, test one safe change, and record what happened.", icon: "1x" },
  { id: "ai-history-generative", title: "History of AI: generative models", heading: "AI moves from classifying to creating", tone: "pink", bullets: ["Earlier AI often labeled or predicted categories.", "Generative AI creates text, images, audio, code, and designs.", "Outputs can be useful, surprising, biased, or wrong.", "Creation raises new questions about truth, ownership, and responsibility." ] },
  { id: "ai-history-multimodal", title: "History of AI: multimodal systems", heading: "Text, image, sound, and code begin to connect", tone: "green", bullets: ["Multimodal models can work across more than one kind of input.", "They may describe images, answer about diagrams, or generate code from instructions.", "The more inputs a model uses, the more ways it can help or misunderstand.", "Clear evidence and careful prompts become even more important." ] },
  { id: "ai-history-open-source", title: "History of AI: local and open models", heading: "Power moves closer to users", tone: "purple", bullets: ["Open model releases let more people study and run AI systems.", "Local tools allow schools and makers to experiment without cloud dependence.", "Smaller models can be improved, customized, and evaluated for specific tasks.", "Access expands, but safety and misuse questions expand too." ] },
  { id: "what-diffusion", title: "What is an image model?", heading: "From noise toward a prompt", tone: "green", bullets: ["A diffusion image model begins with random visual noise.", "Repeated steps estimate and remove noise while following text guidance.", "More steps can improve detail but also require more computation.", "Image generation is different from text generation, but both follow learned patterns." ] },
  { id: "where-ai-tools-fit", title: "Where do AI tools fit in a build?", heading: "Coach, checker, explainer, not autopilot", tone: "light", cards: [ { icon: "?", title: "Before", text: "Brainstorm parts, risks, and a plan." }, { icon: "🔍", title: "During", text: "Explain symptoms and suggest safe checks." }, { icon: "🎤", title: "After", text: "Help write a clear demo explanation." } ] },
  { id: "why-human-in-loop", title: "Why keep a human in the loop?", heading: "The AI does not carry the consequence", tone: "pink", bullets: ["A model can suggest a wrong step with confidence.", "A person can inspect physical reality, smell heat, see loose cables, and stop unsafe actions.", "The builder is responsible for safety and evidence.", "Use AI as a second brain, not the final authority." ] },
  { id: "reassembly-order", title: "A practical order", heading: "Install, connect, inspect", tone: "light", bullets: ["Seat the CPU correctly, then install thermal material and the cooler as directed.", "Install RAM and storage while the motherboard area is easy to reach.", "Install the GPU and any required expansion cards.", "Connect front-panel, motherboard, CPU, GPU, storage, and fan cables.", "Inspect for loose screws, blocked fans, or partially seated connectors before power-on." ] },
  { id: "front-panel", title: "The tiny connectors", heading: "Read the motherboard diagram", tone: "purple", bullets: ["PWR SW connects the case power button.", "RESET SW connects the reset button when present.", "POWER LED and HDD LED are polarity-sensitive indicator lights.", "Look for labels such as F_PANEL or JFP1 in the motherboard manual.", "If the machine will not start, recheck the power switch pins and main power connectors first." ] },
  { id: "post", title: "First power-on", heading: "POST is the first checkpoint", tone: "pink", body: "POST means Power-On Self-Test. Watch and listen for fans, display output, status lights, or diagnostic beeps. If something is wrong, shut down and change only one thing at a time.", icon: "POST" },
  { id: "image-prompt", title: "Describe an image", heading: "Subject + style + mood + composition", tone: "purple", body: "Example: A friendly robot repairing a desktop computer, colorful digital illustration, warm workshop lighting, centered composition, clear tools and components.", icon: "ART" },
  { id: "ai-troubleshoot-prompt", title: "Hands-on: troubleshooting prompt", heading: "Describe symptoms like an engineer", tone: "green", bullets: ["Bad: My computer will not work.", "Better: Fans spin, no display, motherboard has a white VGA light, monitor works with another laptop.", "Ask AI for three safe checks only.", "Decide which checks require instructor approval." ] },
  { id: "project-sprint", title: "Project sprint", heading: "Build, test, explain", tone: "pink", bullets: ["Choose one small outcome that can be demonstrated today.", "Make one change at a time and test after every change.", "Use the AI Coach for hints and explanations, not invisible copy-and-paste work.", "Save a working version before trying a risky improvement.", "Prepare to explain one decision you made without AI." ] },
  { id: "ethics-deepfakes", title: "Ethics question 1", heading: "What if generated media looks real?", tone: "light", bullets: ["Images, voices, and videos can be faked or altered.", "Who could be harmed by a convincing fake?", "What labels or rules should schools require?", "How can viewers check before sharing?" ] },
  { id: "ethics-autonomy", title: "Ethics question 2", heading: "Should AI act on its own?", tone: "purple", body: "Some systems can plan steps, call tools, or control devices. Name one task where autonomy is useful and one task where a person should always approve the action first.", icon: "STOP" },
  { id: "power-on-exit", title: "Ethics question 3 + teach back", heading: "Troubleshoot a no-power computer", kicker: "EXIT TICKET", body: "Give a safe three-step diagnostic plan. Your plan must start with observation, change only one variable at a time, and explain where AI advice should stop.", tone: "green" },
];

const dayFiveSlides: CampSlide[] = [
  { id: "demo-day-opening", title: "Go over: demo day launch", heading: "Show what you built and how you thought", kicker: "FINAL DAY", body: "Today is not just about a finished product. It is about explaining decisions, limits, ethics, and next steps like a responsible technologist.", icon: "5", tone: "green" },
  { id: "week-recap", title: "Go over: five-day recap", heading: "Open it. Understand it. Upgrade it. Power it. Explain it.", tone: "light", cards: [ { icon: "1", title: "Inside", text: "Components and safety." }, { icon: "2", title: "Brains", text: "CPU, GPU, training, inference." }, { icon: "3", title: "Memory", text: "RAM, storage, prompts." }, { icon: "4", title: "Build", text: "Reassembly and troubleshooting." }, { icon: "5", title: "Demo", text: "Ethics and next steps." } ] },
  { id: "demo-success-criteria", title: "Go over: success criteria", heading: "A strong demo is clear, honest, and tested", tone: "purple", bullets: ["Show the project or learning artifact.", "Explain what problem it solves or what question it answers.", "Name where AI helped and where human judgment mattered.", "Describe one limitation honestly.", "Invite one question from the audience." ] },
  { id: "ai-history-agi", title: "History of AI: today's AI is not AGI", heading: "Powerful does not mean human-like", tone: "pink", bullets: ["Today's systems can be impressive in narrow and broad language tasks.", "They still lack human experience, responsibility, and reliable truth checking.", "AGI means a more general intelligence, but people disagree about definitions and timelines.", "For now, judge systems by evidence, limits, and real-world effects." ] },
  { id: "ai-history-work", title: "History of AI: tools change work", heading: "Automation changes tasks before it changes whole jobs", tone: "green", bullets: ["Calculators changed math work; spreadsheets changed offices; search changed research.", "AI may automate parts of writing, coding, design, tutoring, analysis, and support.", "Human skills like judgment, empathy, context, and accountability remain important.", "The best question is: which tasks change, and what new skills matter?" ] },
  { id: "ai-history-future-builders", title: "History of AI: students become builders", heading: "The next chapter is not only written by companies", tone: "purple", bullets: ["Open tools let students explore AI safely at smaller scale.", "Communities need people who understand both technology and consequences.", "Local problems can inspire useful, responsible tools.", "Your next project can be small and still meaningful." ] },
  { id: "what-responsible-ai", title: "What is responsible AI?", heading: "Useful, honest, fair, private, and accountable", tone: "light", cards: [ { icon: "✓", title: "Useful", text: "Solves a real problem." }, { icon: "?", title: "Honest", text: "States limits and uncertainty." }, { icon: "=", title: "Fair", text: "Checks who may be harmed." }, { icon: "🔒", title: "Private", text: "Protects sensitive information." } ] },
  { id: "where-ai-careers", title: "Where can AI skills take you?", heading: "Many paths need AI literacy", tone: "green", bullets: ["Computer science: build and test systems.", "Cybersecurity: detect threats and protect data.", "Health, education, and accessibility: design tools for people.", "Hardware and repair: keep systems reliable and efficient.", "Art, media, and communication: create with clear labels and credit." ] },
  { id: "why-keep-learning-ai", title: "Why keep learning?", heading: "AI changes quickly; principles last longer", tone: "pink", bullets: ["Tools will change, but clear thinking remains useful.", "Hardware limits still matter.", "Good prompts still need context, task, format, and constraints.", "Ethics still asks: who benefits, who is harmed, and who is responsible?" ] },
  { id: "ethics-opening", title: "AI ethics", heading: "Power creates responsibility", tone: "purple", body: "Ethics asks what we should do, who may be helped or harmed, and who is responsible. The goal is not one perfect answer; it is a reasoned answer that considers evidence and people.", icon: "?" },
  { id: "hiring-bias", title: "Scenario: hiring data", heading: "Can an algorithm repeat unfair history?", tone: "pink", body: "A company trains a hiring model on ten years of past decisions. The model begins favoring the same schools and demographic groups found in that history.", bullets: ["Who is responsible for checking the result?", "Can the model be fixed without examining the underlying data and process?", "What evidence would a fair audit require?"] },
  { id: "privacy", title: "Scenario: phone data", heading: "What does informed consent mean?", tone: "light", body: "Phones and apps can collect location, searches, usage patterns, contacts, photos, and device information to personalize services.", bullets: ["Is a long terms-of-service screen meaningful consent?", "What data is necessary for the feature and what data is merely valuable to collect?", "What controls should every user receive?"] },
  { id: "creative-ownership", title: "Scenario: creative work", heading: "Training data, credit, and ownership", tone: "green", body: "Generative models may learn from large collections that include copyrighted work. New outputs can resemble styles, patterns, and material found in those collections.", bullets: ["What should creators be told or allowed to choose?", "Who should receive credit or payment?", "How would you label AI-assisted work honestly?"] },
  { id: "jobs", title: "Scenario: changing jobs", heading: "Automation replaces tasks and creates tasks", tone: "purple", bullets: ["Which parts of a job require trust, judgment, responsibility, or human relationships?", "Which repetitive tasks might be automated first?", "What new skills become valuable when AI tools are common?", "How can organizations share benefits without ignoring displaced workers?"] },
  { id: "demo-format", title: "Demo format", heading: "Show the work, not just the result", tone: "pink", bullets: ["What does the project do? Demonstrate it live when possible.", "How did you build it, and where did AI help?", "What decision or improvement are you proud of?", "What problem remains, and what would you add next?", "Audience response: one thing I liked and one question I have."] },
  { id: "ai-pledge", title: "Ethics question 1", heading: "What will your AI rule be?", tone: "light", body: "Write one personal rule for using AI this year. It should protect learning, privacy, fairness, or truth. Example: I will use AI to explain ideas, not to hide what I do not understand.", icon: "RULE" },
  { id: "next-path", title: "Ethics question 2 + next path", heading: "Keep building after camp", tone: "green", cards: [ { icon: "</>", title: "Coding", text: "Build another web project and keep it in a Git repository." }, { icon: "PC", title: "Hardware", text: "Practice compatibility research, repair, and CompTIA A+ skills." }, { icon: "AI", title: "Artificial intelligence", text: "Compare models, study evaluation, and build responsible local tools." }, { icon: "+", title: "All three", text: "Try robotics, hackathons, maker spaces, or a community technology project." } ] },
  { id: "final-reflection", title: "Ethics question 3 + final reflection", heading: "Open it. Upgrade it. Run it. Explain it.", kicker: "FINAL REFLECTION", body: "In five days you investigated computer hardware, ran local AI, improved prompts, troubleshot systems, built a project, and considered responsible use. Write the next thing you want to learn and the first action you will take.", icon: "5", tone: "green" },
];

export const campDays: CampDay[] = [
  { number: 1, title: "Open It Up", subtitle: "Hardware foundations and local AI", slides: dayOneSlides },
  { number: 2, title: "The Brains", subtitle: "CPU, GPU, training, and inference", slides: dayTwoSlides },
  { number: 3, title: "Upgrade Lab", subtitle: "Memory, storage, and better prompts", slides: dayThreeSlides },
  { number: 4, title: "Power On", subtitle: "Reassembly, troubleshooting, and building", slides: dayFourSlides },
  { number: 5, title: "Demo Day", subtitle: "AI ethics, presentation, and next steps", slides: dayFiveSlides },
];
