/**
 * Appears under every AI-generated response. Keep the copy centralized here
 * so wording can be reviewed/changed in one place without touching layout code.
 */
const DISCLAIMER_TEXT =
  "Generated by local AI — check important facts. REACT Camp sends prompts only to Ollama on this computer.";

export function DisclaimerFooter() {
  return <p className="disclaimer-footer">{DISCLAIMER_TEXT}</p>;
}
